# ==============================================================================
# Mullvad DNS - DNS-over-TLS (DoT) Provider
# ==============================================================================
# Strict zero-logging, Swedish privacy jurisdiction.
# ==============================================================================

[Resolve]
DNS=194.242.2.2#dns.mullvad.net 193.19.108.2#dns.mullvad.net 2a07:e340::2#dns.mullvad.net
FallbackDNS=1.1.1.1#cloudflare-dns.com 9.9.9.9#dns.quad9.net
DNSOverTLS=yes
DNSSEC=allow-downgrade
MulticastDNS=yes
LLMNR=resolve
Cache=yes
